title: Diário de Bordo
baseurl: "/dsl-patch-blog"
# ajuste aqui se o site estiver em um subdiretório (ex: "/nome-do-repo")
permalink: /:year/:month/:day/:title/
highlighter: rouge
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    default_lang: text
author: César Augusto
