title: Diário de Bordo
baseurl: "/dsl-patch-blog"
# ajuste aqui se o site estiver em um subdiretório (ex: "/nome-do-repo")
permalink: /:year/:month/:day/:title/
markdown: kramdown
author: César Augusto
highlighter: rouge
